### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by seaneking** [SimplaElements/simpla-text#27]
#29 Simpla-text needs to be rebuilt from the ground up to polished and ready for 1.0. The biggest change will be replacing Scribe with a modern, abstracted richtext framework that doesn't rely on the native (broken) contenteditable API.

Major components:
- [ ] Replace Scribe with abstracted framework (Draft, Slate, Quill) and abstract/split out to `simpla-richtext-behavior`.
- [ ] Generalise [sm-ui-toolbar](https://github.com/SimplaElements/sm-ui-toolbar) into resusable singleton, not tightly bound to text
- [ ] Remove placeholder element, use pure CSS solution instead (fixes #26 and other issues)
- [ ] Seperate editing/viewing logic (editor should not be loaded at all until/if edit mode)
- [ ] Move to Simpla SDK (replace all `utility` components)
- [ ] Tests
- [ ] Rethink and consolidate interface (properties, methods). Make any breaking changes we need to.
- [ ] Migrate to Polymer 2.0 _or_ SkateJS

**Comment by seaneking** [comment]
Worth holding off on this until Polymer 2.0 is released mainline, and upgrade to that at the same time. Will update tasklist to reflect.

**Comment by seaneking** [comment]
Looking into richtext frameworks a bit more, Draft and Slate are really our only long-term viable options. They're both built on React, which would _almost_ make them untenable for the weight, **but** there's [preact-compat](https://github.com/developit/preact-compat) 🎉 . They _should_ in theory work with that, which means only a 3kb dep. If one of them works with preact then that's decision made, IMO.

**Comment by bedeoverend** [comment]
@seaneking I had a play with Slate + preact-compat a little while back, it looks good, couldn't do much though because its an absolute nightmare to get a react app wired up and working. Unfortunately slate I'm pretty sure still [injects a wrapper contenteditable div](https://github.com/ianstormtaylor/slate/blob/master/src/components/content.js#L652) into the element. It isn't necessarily the end of the world, but it's a real pain in the ass. Note that we've been wrapping content during editing on Shady DOM browsers anyway, and so far hasn't been an issue.

Also re: size - I don't think we should stress too much about the size. Given we're only going to load in the functionality when Simpla becomes editable, it's ok if it takes a moment to load in those dependencies.

**Comment by bedeoverend** [comment]
And wow, looks like Draft [wraps up their content in 3 divs](https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditor.react.js#L229) 😒

**Comment by seaneking** [comment]
It's only while editing though, so as long as those elements don't have any styling associated to them it _should_ be okay. The only edge case is if someone has relied on direct children for styling (ie: `simpla-text > p`), which will break just in editing. If that's the biggest problem with simpla-text, I'd be very happy.

That said we should def look into if we can somehow keep their wrappers in shadow dom and reflect content to light dom, even if we just clone the content and hide the shadow dom stuff, or something to that effect.

**Comment by bedeoverend** [comment]
What frustrates me, all we need (in my limited understanding of react) is just that `render` function inside Slate to attach all those attributes / listeners etc. onto `simpla-text`.

As for the wrapper thing, unfortunately already tried that (though maybe try again with the new shadow DOM API) - essentially the `contenteditable` attribute element _must_ be in the light DOM - contenteditable has no affect trying to pierce through the Shadow DOM boundary. so `<div contenteditable><slot></slot></div>` doesn't work. Anyway, worth investigating again.

**Comment by bedeoverend** [comment]
I take it all back. Made a quick [pen](http://codepen.io/bedeoverend/pen/jrwJbp) looks like it's working in the new v1, very very nice. That works on FF too using https://github.com/skatejs/named-slots polyfill. Still wouldn't work with Slate / Draft out of the box, but opens up a few doors.

**Comment by bedeoverend** [comment]
Just to clarify on the content editable and slot, it does work in some browsers, but it [definitely is a bug](https://github.com/w3c/webcomponents/issues/579) and shouldn't happen.

**Comment by seaneking** [comment]
Shipped in https://github.com/SimplaElements/simpla-text/releases/tag/v1.0.0
